### ISSUE TITLE
Ensure timeseries stationary

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/ist-736#105]
We need to induce stationarity for our timeseries, otherwise our model generation, and successive analysis may prematurely terminate:

```bash
[...INITIAL-TRACE-OMITTED...]
Traceback (most recent call last):
  File "app.py", line 94, in <module>
    stopwords=stopwords
  File "C:\Users\jeff1\web-projects\ist-736\app\analysis.py", line 96, in analyze
    lstm_epochs=50
  File "C:\Users\jeff1\web-projects\ist-736\brain\controller\timeseries.py", line 44, in timeseries
    date_index=date_index
  File "C:\Users\jeff1\web-projects\ist-736\brain\model\timeseries.py", line 32, in model
    model.train(iterations=iterations)
  File "C:\Users\jeff1\web-projects\ist-736\brain\algorithm\arima.py", line 112, in train
    model_fit = model.fit(disp=0)
  File "C:\Python36\lib\site-packages\statsmodels\tsa\arima_model.py", line 946, in fit
    start_ar_lags)
  File "C:\Python36\lib\site-packages\statsmodels\tsa\arima_model.py", line 562, in _fit_start_params
    start_params = self._fit_start_params_hr(order, start_ar_lags)
  File "C:\Python36\lib\site-packages\statsmodels\tsa\arima_model.py", line 541, in _fit_start_params_hr
    raise ValueError("The computed initial AR coefficients are not "
ValueError: The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
```

**Comment by jeff1evesque** [comment]
This issue was prematurely closed.
