### ISSUE TITLE
Implement peak detection for classification labeling

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/ist-736#98]
We need to implement our defined peak detection class from #88.

**Comment by jeff1evesque** [comment]
We've added and implemented our untested `peak_detection` logic. Moreover, we should extend our logic to allow multiple z-score thresholds. Specifically, an array of thresholds can be provided, and the returned index would return a higher index value respectively.

**Comment by jeff1evesque** [comment]
We'll need to test the overall code, and make adjustments respectively. Furthermore, the `write-up.docx` will need the associated language modified:

>To begin, stock prices (y) were binned into two classes (up, down)  (0, 1). Specifically, “up” was assigned if the current day Index Value was greater than the previous day; otherwise, assigned down.

**Comment by jeff1evesque** [comment]
We'll need to test the overall code, and make adjustments respectively. Furthermore, the `write-up.docx` will need the associated language modified:

>To begin, stock prices (y) were binned into two classes (up, down) -> (0, 1). Specifically, “up” was assigned if the current day Index Value was greater than the previous day; otherwise, assigned down.

**Comment by jeff1evesque** [comment]
Our corresponding plotting efforts of the z-score peak detection indicates a mismatch of dimensions:

```bash
[...INITIAL-TRACE-OMITTED...]
See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  current=data[sn][classify_index][i]
Traceback (most recent call last):
  File "app.py", line 78, in <module>
    stopwords=stopwords
  File "C:\Users\jeff1\web-projects\ist-736\app\analysis.py", line 191, in analyze
    suffix=sn
  File "C:\Users\jeff1\web-projects\ist-736\brain\controller\peak_detection.py", line 52, in peak_detection
    lw=2
  File "C:\Python36\lib\site-packages\matplotlib\pyplot.py", line 2813, in plot
    is not None else {}), **kwargs)
  File "C:\Python36\lib\site-packages\matplotlib\__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)
  File "C:\Python36\lib\site-packages\matplotlib\axes\_axes.py", line 1611, in plot
    for line in self._get_lines(*args, **kwargs):
  File "C:\Python36\lib\site-packages\matplotlib\axes\_base.py", line 393, in _grab_next_args
    yield from self._plot_args(this, kwargs)
  File "C:\Python36\lib\site-packages\matplotlib\axes\_base.py", line 370, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "C:\Python36\lib\site-packages\matplotlib\axes\_base.py", line 231, in _xy_from_xy
    "have shapes {} and {}".format(x.shape, y.shape))
ValueError: x and y must have same first dimension, but have shapes (20,) and (2, 20)
```
